Repository OpenDevicePartnership/mimxrt685s-pac, pull requests merged in 2025-02, with the labels that each got.

#10 Draft initial project documents
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
  SECURITY.md
Labels: documentation

#11 Patch ADC RESFIFO field D
  Cargo.toml
  patch/adc.yaml
  src/adc0/resfifo.rs
Labels: enhancement

#12 CRC WR_DATA access sizes
  Cargo.toml
  patch/MIMXRT685S_cm33.yaml
  patch/crc.yaml
  src/crc_engine.rs
  src/crc_engine/mode.rs
  src/crc_engine/wr_data16.rs
  src/crc_engine/wr_data32.rs
  src/crc_engine/wr_data8.rs
Labels: bug, breaking change

#16 Patch CTIMER IR register to be W1C
  Cargo.toml
  patch/MIMXRT685S_cm33.yaml
  patch/ctimer.yaml
  src/ctimer0/ir.rs
Labels: bug
